#compose.yaml
version : "3.1"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3308:3306"
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  php-apache:
    volumes:
      - "./app:/var/www/html"
    ports:
      - "8000:80"
    build:
      context: ./
      dockerfile: dockerfile